FULL = 'FULL'
DECLINED = 'Declined'
NOT_PERFORMED = 'Not performed'
BASELINE_CODES = ['T0']
ANNUAL_CODES = ['T1', 'T2', 'T3']
ANNUAL = 'annual'
PIMA_VL_TYPE = 'Mobile settings'
CENTRAL_SERVER = 'central'
FIELD_SUPERVISOR_GROUP = 'field_supervisor'
FIELD_RESEARCH_ASSISTANT_GROUP = 'field_research_assistant'