from electrical_appliances import ElectricalAppliances
from transport_mode import TransportMode
from live_with import LiveWith
from neighbourhood_problems import NeighbourhoodProblems
from circumcision_benefits import CircumcisionBenefits
from family_planning import FamilyPlanning
from medical_care_access import MedicalCareAccess
from household_survey_code import HouseholdSurveyCode
from household_survey_reason import HouseholdSurveyReason
from household_survey_source import HouseholdSurveySource
from survey_group import SurveyGroup
from household_structure_relation import HouseholdStructureRelation
from household_survey_status import HouseholdSurveyStatus

from subject_absentee_reason import SubjectAbsenteeReason
from subject_moved_reason import SubjectMovedReason
from subject_undecided_reason import SubjectUndecidedReason

from partner_residency import PartnerResidency
from heart_disease import HeartDisease
from diagnoses import Diagnoses
from religion import Religion
from ethnic_groups import EthnicGroups

from referred_to import ReferredTo
from referred_for import ReferredFor

from sti_illnesses import StiIllnesses

from resident_most_likely import ResidentMostLikely