from .demographics_risk_admin import DemographicsRiskAdmin
from .partners_admin import HtcRecentPartnerAdmin, HtcSecondPartnerAdmin, HtcThirdPartnerAdmin
from .htc_subject_visit_admin import HtcSubjectVisitAdmin
from .htc_registration_admin import HtcRegistrationAdmin
from .htc_circumcision_admin import HtcCircumcisionAdmin
from .htc_hiv_testing_history_admin import HtcHivTestingHistoryAdmin
from .last_hiv_record_admin import LastHivRecordAdmin
from .hiv_testing_consent_admin import HivTestingConsentAdmin
from .htc_hiv_result_admin import HtcHivResultAdmin
from .referral_admin import ReferralAdmin
from .cd4_test_admin import Cd4TestAdmin
from .circumcision_appointment_admin import CircumcisionAppointmentAdmin
from .positive_followup_admin import PositiveFollowupAdmin
from .male_followup_admin import MaleFollowupAdmin
from .pregnant_followup_admin import PregnantFollowupAdmin
