from .main import *

from .access_to_care_admin import AccessToCareAdmin
from .cd4_history_admin import Cd4HistoryAdmin
from .cea_enrolment_checklist_admin import CeaEnrolmentChecklistAdmin
from .circumcision_admin import CircumcisionAdmin, UncircumcisedAdmin, CircumcisedAdmin
from .community_engagement_admin import CommunityEngagementAdmin
from .demographics_admin import DemographicsAdmin
from .education_admin import EducationAdmin
from .future_hiv_testing_admin import FutureHivTestingAdmin
from .grant_admin import GrantAdmin
from .hiv_care_adherence_admin import HivCareAdherenceAdmin
from .hiv_result_admin import HivResultAdmin
from .hiv_test_review_admin import HivTestReviewAdmin
from .hiv_tested_admin import HivTestedAdmin
from .hiv_testing_history_admin import HivTestingHistoryAdmin
from .hiv_untested_admin import HivUntestedAdmin
from .labour_market_wages_admin import LabourMarketWagesAdmin, GrantInlineAdmin
from .medical_diagnoses_admin import MedicalDiagnosesAdmin
from .months_partner_admin import *
from .non_pregnancy_admin import NonPregnancyAdmin
# from .partner_admin import RecentPartnerAdmin, SecondPartnerAdmin, ThirdPartnerAdmin
from .pima_admin import PimaAdmin
from .postitive_participant_admin import PositiveParticipantAdmin
from .pregnancy_admin import PregnancyAdmin
from .reproductive_health_admin import ReproductiveHealthAdmin
from .residency_mobility_admin import ResidencyMobilityAdmin
from .sexual_behaviour_admin import SexualBehaviourAdmin
from .stigma_admin import StigmaAdmin
from .stigma_opinion_admin import StigmaOpinionAdmin
from .subject_absentee_admin import *
from .subject_consent_admin import SubjectConsentAdmin, SubjectConsentRbdAdmin
from .subject_death_admin import SubjectDeathAdmin
from .subject_locator_admin import SubjectLocatorAdmin
from .subject_moved_admin import SubjectMovedAdmin
from .subject_referral_admin import SubjectReferralAdmin
from .subject_refusal_admin import SubjectRefusalAdmin
from .subject_undecided_admin import *
from .subject_visit_admin import SubjectVisitAdmin
from .hiv_result_documentation_admin import HivResultDocumentationAdmin
from .clinic_questionnaire_admin import ClinicQuestionnaireAdmin
