from .landmarks import (DIGAWANA_LANDMARKS, MOLAPOWABOJANG_LANDMARKS, OTSE_LANDMARKS, RANAKA_LANDMARKS, BOKAA_LANDMARKS,
                        OODI_LANDMARKS, LENTSWELETAU_LANDMARKS, LETLHAKENG_LANDMARKS, MMATHETHE_LANDMARKS,
                        MMANKGODI_LANDMARKS, SEFOPHE_LANDMARKS, LERALA_LANDMARKS, MAUNATLALA_LANDMARKS,
                        RAMOKGONAMI_LANDMARKS, SHOSHONG_LANDMARKS, MMADINARE_LANDMARKS, METSIMOTLHABE_LANDMARKS,
                        TATI_SIDING_LANDMARKS, NKANGE_LANDMARKS, SEBINA_LANDMARKS, MATHANGWANE_LANDMARKS,
                        MMANDUNYANE_LANDMARKS, RAKOPS_LANDMARKS, GWETA_LANDMARKS, GUMARE_LANDMARKS, SHAKAWE_LANDMARKS,
                        MASUNGA_LANDMARKS, NATA_LANDMARKS, SEFHARE_LANDMARKS, TSETSEBJWE_LANDMARKS)
from .sections_and_sub_sections import SECTIONS, SUB_SECTIONS
