# LAB_IMPORT_DMIS_DATA_SOURCE = ('DRIVER=/usr/local/lib/libtdsodbc.so;SERVER=localhost;PORT=2003;UID=sa;PWD=cc3721b;DATABASE=BHPLAB')
LAB_IMPORT_DMIS_DATA_SOURCE = ('DRIVER=/usr/local/lib/libtdsodbc.so;SERVER=192.168.1.10;PORT=1433;UID=sa;PWD=cc3721b;DATABASE=BHPLAB')
