from natural_key_tests import NaturalKeyTests
from household_mapper_tests import HouseholdMapperTests
from plot_tests import PlotTests
from household_tests import HouseholdTests
from household_confirmation_tests import HouseholdConfirmTests
from plot_replacement_methods_tests import PlotReplacementTests
