# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_household_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhouseholdmember',
            name='member_status',
            field=models.CharField(choices=[('BHS_SCREEN', 'BHS_SCREEN'), ('NOT_ELIGIBLE', 'NOT_ELIGIBLE'), ('REFUSED_HTC', 'REFUSED_HTC'), ('ANNUAL', 'ANNUAL'), ('DECEASED', 'DECEASED'), ('BHS', 'BHS'), ('UNDECIDED', 'UNDECIDED'), ('BHS_LOSS', 'BHS_LOSS'), ('HTC', 'HTC'), ('HTC_ELIGIBLE', 'HTC_ELIGIBLE'), ('REFUSED', 'REFUSED'), ('BHS_ELIGIBLE', 'BHS_ELIGIBLE'), ('NOT_REPORTED', 'NOT_REPORTED'), ('ABSENT', 'ABSENT')], db_index=True, editable=False, help_text='RESEARCH, ABSENT, REFUSED, UNDECIDED', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='member_status',
            field=models.CharField(choices=[('BHS_SCREEN', 'BHS_SCREEN'), ('NOT_ELIGIBLE', 'NOT_ELIGIBLE'), ('REFUSED_HTC', 'REFUSED_HTC'), ('ANNUAL', 'ANNUAL'), ('DECEASED', 'DECEASED'), ('BHS', 'BHS'), ('UNDECIDED', 'UNDECIDED'), ('BHS_LOSS', 'BHS_LOSS'), ('HTC', 'HTC'), ('HTC_ELIGIBLE', 'HTC_ELIGIBLE'), ('REFUSED', 'REFUSED'), ('BHS_ELIGIBLE', 'BHS_ELIGIBLE'), ('NOT_REPORTED', 'NOT_REPORTED'), ('ABSENT', 'ABSENT')], db_index=True, editable=False, help_text='RESEARCH, ABSENT, REFUSED, UNDECIDED', max_length=25, null=True),
        ),
    ]
