ACCESSIBLE = 'accessible'
BASELINE_SURVEY_SLUG = 'bcpp-year-1'
CONFIRMED = 'confirmed'
DECEASED = 'deceased'
ELIGIBLE_REPRESENTATIVE_ABSENT = 'eligible_representative_absent'
ELIGIBLE_REPRESENTATIVE_PRESENT = 'eligible_representative_present'
FIVE_PERCENT = '2'  # plot.selected=2
INACCESSIBLE = 'inaccessible'
NEARLY_ALWAYS_OCCUPIED = 'nearly_always_present'  # replace
NEVER_OCCUPIED = 'never_occupied'  # NOT replaced
NON_RESIDENTIAL = 'non_residential'
NO_HOUSEHOLD_INFORMANT = 'no_household_informant'
RARELY_OCCUPIED = 'rarely_occupied'  # NOT replaced
REFUSED_ENUMERATION = 'refused'
RESIDENTIAL_HABITABLE = 'residential_habitable'
RESIDENTIAL_NOT_HABITABLE = 'residential_not_habitable'
SEASONALLY_OCCUPIED = 'seasonally_occupied'  # replace
SEVENTY_FIVE_PERCENT = None
TWENTY_PERCENT = '1'
UNCONFIRMED = 'unconfirmed'
UNKNOWN_OCCUPIED = 'unknown'  # replaced
VISIT_ATTEMPTS = 3
