from forms_tests import FormsTests
#from off_study_tests import OffStudyTests
from factory_tests import FactoryTests
from natural_key_tests import NaturalKeyTests
from choice_tests import ChoiceTests
from consent_history_tests import ConsentHistoryTests
#from selenium_tests import SeleniumTests
#from erik_tests import ErikTests
from consent_tests import ConsentTests
from .referral_tests import ReferralTests
