from dateutil.relativedelta import MO, TU, WE, TH, FR

BCPP_CLINIC_DAYS = {
    '11': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '12': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '13': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '14': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '15': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '16': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '17': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '18': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '19': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '20': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '21': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '22': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '23': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '24': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '25': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '26': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '27': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '28': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '29': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '30': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '31': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '32': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '33': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '34': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '35': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '36': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '37': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '38': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '39': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    '40': {'IDCC': (MO, WE), 'ANC': (MO, TU, WE, TH, FR), 'SMC': (MO, TU, WE, TH, FR), 'SMC-ECC': (MO, TU, WE, TH, FR)},
    }
