DEVICE_ID = 99
SITE_CODE = '11'
CURRENT_COMMUNITY = 'ranaka'
VERIFY_GPS = False if DEVICE_ID == 99 else True
VERIFY_GPS_LOCATION = False if DEVICE_ID == 99 else True
VERIFY_PLOT_COMMUNITY_WITH_CURRENT_MAPPER = False if DEVICE_ID == 99 else True
