DEVICE_ID = 82
SITE_CODE = '12'
CURRENT_COMMUNITY = 'digawana'
ADMIN_EXCLUDE_DEFAULT_CODE = 'T1'
VERIFY_GPS = False if DEVICE_ID == 99 else False
VERIFY_GPS_LOCATION = False
VERIFY_PLOT_COMMUNITY_WITH_CURRENT_MAPPER = False if DEVICE_ID == 99 else True
