DEVICE_ID = 99
SITE_CODE = '01'
CURRENT_COMMUNITY = 'test_community'
VERIFY_GPS = False if DEVICE_ID == 99 else True
VERIFY_GPS_LOCATION = False if DEVICE_ID == 99 else True
VERIFY_PLOT_COMMUNITY_WITH_CURRENT_MAPPER = False if DEVICE_ID == 99 else True
