import factory
from datetime import date, datetime
from bhp_base_model.tests.factories import BaseUuidModelFactory
from bcpp_subject.models import BaselineHouseholdSurvey


class BaselineHouseholdSurveyFactory(BaseUuidModelFactory):
    FACTORY_FOR = BaselineHouseholdSurvey

    report_datetime = datetime.today()
    flooring_type = (('Dirt/earth', <django.utils.functional.__proxy__ object at 0x103a20e50>), ('Wood, plank', <django.utils.functional.__proxy__ object at 0x103a20ed0>), ('Parquet/lino', <django.utils.functional.__proxy__ object at 0x103a20f50>), ('Cement', <django.utils.functional.__proxy__ object at 0x103a20fd0>), ('Tile flooring', <django.utils.functional.__proxy__ object at 0x103a22090>), ('OTHER', <django.utils.functional.__proxy__ object at 0x103a22110>), ("Don't want to answer", <django.utils.functional.__proxy__ object at 0x103a22190>))[0][0]
    flooring_type_other = factory.Sequence(lambda n: 'flooring_type_other{0}'.format(n))
    water_source = (('Communal tap', <django.utils.functional.__proxy__ object at 0x103a22210>), ('Standpipe/tap within plot', <django.utils.functional.__proxy__ object at 0x103a22290>), ('Piped indoors', <django.utils.functional.__proxy__ object at 0x103a22310>), ('Borehore', <django.utils.functional.__proxy__ object at 0x103a22390>), ('Protected well', <django.utils.functional.__proxy__ object at 0x103a22410>), ('Unprotected/shallow well', <django.utils.functional.__proxy__ object at 0x103a22490>), ('River /dam/lake/pan', <django.utils.functional.__proxy__ object at 0x103a22510>), ('Bowser/tanker', <django.utils.functional.__proxy__ object at 0x103a22590>), ('OTHER', <django.utils.functional.__proxy__ object at 0x103a22610>), ("Don't want to answer", <django.utils.functional.__proxy__ object at 0x103a22690>))[0][0]
    water_source_other = factory.Sequence(lambda n: 'water_source_other{0}'.format(n))
    energy_source = (('Charcoal/wood', <django.utils.functional.__proxy__ object at 0x103a22710>), ('Paraffin', <django.utils.functional.__proxy__ object at 0x103a22790>), ('Gas', <django.utils.functional.__proxy__ object at 0x103a22810>), ('Electricity (mains)', <django.utils.functional.__proxy__ object at 0x103a22890>), ('Electricity (solar)', <django.utils.functional.__proxy__ object at 0x103a22910>), ('No cooking done', <django.utils.functional.__proxy__ object at 0x103a22990>), ('OTHER', <django.utils.functional.__proxy__ object at 0x103a22a10>), ("Don't want to answer", <django.utils.functional.__proxy__ object at 0x103a22a90>))[0][0]
    energy_source_other = factory.Sequence(lambda n: 'energy_source_other{0}'.format(n))
    toilet_facility = (('Pit latrine within plot', <django.utils.functional.__proxy__ object at 0x103a22b10>), ('Flush toilet within plot', <django.utils.functional.__proxy__ object at 0x103a22b90>), ("Neighbour's flush toilet", <django.utils.functional.__proxy__ object at 0x103a22c10>), ("Neighbour's pit latrine", <django.utils.functional.__proxy__ object at 0x103a22c90>), ('Communal flush toilet', <django.utils.functional.__proxy__ object at 0x103a22d10>), ('Communal pit latrine', <django.utils.functional.__proxy__ object at 0x103a22d90>), ('Pail bucket latrine', <django.utils.functional.__proxy__ object at 0x103a22e10>), ('Bush', <django.utils.functional.__proxy__ object at 0x103a22e90>), ('River or other body of water', <django.utils.functional.__proxy__ object at 0x103a22f10>), ('OTHER', <django.utils.functional.__proxy__ object at 0x103a22f90>), ("Don't want to answer", <django.utils.functional.__proxy__ object at 0x103a23050>))[0][0]
    toilet_facility_other = factory.Sequence(lambda n: 'toilet_facility_other{0}'.format(n))
    smaller_meals = (('Never', <django.utils.functional.__proxy__ object at 0x103a230d0>), ('Rarely', <django.utils.functional.__proxy__ object at 0x103a23150>), ('Sometimes', <django.utils.functional.__proxy__ object at 0x103a231d0>), ('Often', <django.utils.functional.__proxy__ object at 0x103a23250>), ("Don't want to answer", <django.utils.functional.__proxy__ object at 0x103a232d0>))[0][0]
