import factory
from datetime import date, datetime
from bhp_base_model.tests.factories import BaseUuidModelFactory
from bcpp_subject.models import StigmaOpinion


class StigmaOpinionFactory(BaseUuidModelFactory):
    FACTORY_FOR = StigmaOpinion

    report_datetime = datetime.today()
    test_community_stigma = (('Strongly disagree', <django.utils.functional.__proxy__ object at 0x103ae2dd0>), ('Disagree', <django.utils.functional.__proxy__ object at 0x103ae2e50>), ('Uncertain', <django.utils.functional.__proxy__ object at 0x103ae2ed0>), ('Agree', <django.utils.functional.__proxy__ object at 0x103ae2f50>), ('Strongly agree', <django.utils.functional.__proxy__ object at 0x103ae2fd0>), ("Don't want to answer", <django.utils.functional.__proxy__ object at 0x103ae4090>))[0][0]
    gossip_community_stigma = (('Strongly disagree', <django.utils.functional.__proxy__ object at 0x103ae2dd0>), ('Disagree', <django.utils.functional.__proxy__ object at 0x103ae2e50>), ('Uncertain', <django.utils.functional.__proxy__ object at 0x103ae2ed0>), ('Agree', <django.utils.functional.__proxy__ object at 0x103ae2f50>), ('Strongly agree', <django.utils.functional.__proxy__ object at 0x103ae2fd0>), ("Don't want to answer", <django.utils.functional.__proxy__ object at 0x103ae4090>))[0][0]
    respect_community_stigma = (('Strongly disagree', <django.utils.functional.__proxy__ object at 0x103ae2dd0>), ('Disagree', <django.utils.functional.__proxy__ object at 0x103ae2e50>), ('Uncertain', <django.utils.functional.__proxy__ object at 0x103ae2ed0>), ('Agree', <django.utils.functional.__proxy__ object at 0x103ae2f50>), ('Strongly agree', <django.utils.functional.__proxy__ object at 0x103ae2fd0>), ("Don't want to answer", <django.utils.functional.__proxy__ object at 0x103ae4090>))[0][0]
    enacted_verbal_stigma = (('Strongly disagree', <django.utils.functional.__proxy__ object at 0x103ae2dd0>), ('Disagree', <django.utils.functional.__proxy__ object at 0x103ae2e50>), ('Uncertain', <django.utils.functional.__proxy__ object at 0x103ae2ed0>), ('Agree', <django.utils.functional.__proxy__ object at 0x103ae2f50>), ('Strongly agree', <django.utils.functional.__proxy__ object at 0x103ae2fd0>), ("Don't want to answer", <django.utils.functional.__proxy__ object at 0x103ae4090>))[0][0]
    enacted_phyical_stigma = (('Strongly disagree', <django.utils.functional.__proxy__ object at 0x103ae2dd0>), ('Disagree', <django.utils.functional.__proxy__ object at 0x103ae2e50>), ('Uncertain', <django.utils.functional.__proxy__ object at 0x103ae2ed0>), ('Agree', <django.utils.functional.__proxy__ object at 0x103ae2f50>), ('Strongly agree', <django.utils.functional.__proxy__ object at 0x103ae2fd0>), ("Don't want to answer", <django.utils.functional.__proxy__ object at 0x103ae4090>))[0][0]
    enacted_family_stigma = (('Strongly disagree', <django.utils.functional.__proxy__ object at 0x103ae2dd0>), ('Disagree', <django.utils.functional.__proxy__ object at 0x103ae2e50>), ('Uncertain', <django.utils.functional.__proxy__ object at 0x103ae2ed0>), ('Agree', <django.utils.functional.__proxy__ object at 0x103ae2f50>), ('Strongly agree', <django.utils.functional.__proxy__ object at 0x103ae2fd0>), ("Don't want to answer", <django.utils.functional.__proxy__ object at 0x103ae4090>))[0][0]
    fear_stigma = (('Strongly disagree', <django.utils.functional.__proxy__ object at 0x103ae2dd0>), ('Disagree', <django.utils.functional.__proxy__ object at 0x103ae2e50>), ('Uncertain', <django.utils.functional.__proxy__ object at 0x103ae2ed0>), ('Agree', <django.utils.functional.__proxy__ object at 0x103ae2f50>), ('Strongly agree', <django.utils.functional.__proxy__ object at 0x103ae2fd0>), ("Don't want to answer", <django.utils.functional.__proxy__ object at 0x103ae4090>))[0][0]
