from main import *
from demographics_risk_admin import DemographicsRiskAdmin
from partners_admin import RecentPartnerAdmin, SecondPartnerAdmin, ThirdPartnerAdmin
from htc_visit_admin import HtcVisitAdmin
from circumcision_admin import CircumcisionAdmin
from hiv_testing_history_admin import HivTestingHistoryAdmin
from last_hiv_record_admin import LastHivRecordAdmin
from hiv_testing_consent_admin import HivTestingConsentAdmin
from hiv_result_admin import HivResultAdmin
from referral_admin import ReferralAdmin
from cd4_test_admin import CD4TestAdmin
from circumcision_appointment_admin import CircumcisionAppointmentAdmin
from positive_followup_consent_admin import PositiveFollowupConsentAdmin
from male_followup_consent_admin import MaleFollowupConsentAdmin
from pregnant_followup_consent_admin import PregnantFollowupConsentAdmin
