from os_variables import *
from check_initials_field import *
from check_omang_field import *
from age import *
from round_up import *
from get_age_in_days import *
from check_dashboard_redirect import *
from get_ip_address import get_ip_address
from get_iface_list import get_iface_list
