LOCAL_APPS = (
    'apps.bcpp',
    'apps.bcpp.app_configuration',
    'apps.bcpp_list',
    'apps.bcpp_dashboard',
    'apps.bcpp_stats',
    'apps.bcpp_household',
    'apps.bcpp_subject',
    'apps.bcpp_household_member',
    'apps.bcpp_lab',
    'apps.bcpp_survey',
    'apps.bcpp_inspector',
    'apps.bcpp_dispatch',
    'apps.bcpp_analytics',
    'apps.bcpp_clinic',
    'apps.bcpp_clinic_sync',
)
