# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 19:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields
import django_revision.revision_field
import edc_base.model.fields.hostname_modification_field
import edc_base.model.fields.userfield
import edc_base.model.fields.uuid_auto_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('survey_name', models.CharField(db_index=True, help_text='format is, form example, BCPP Year 1', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('BCPP\\ Year\\ [0-9]{1}')], verbose_name='Survey name')),
                ('survey_abbrev', models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Survey name abbreviation')),
                ('survey_description', models.CharField(blank=True, db_index=True, max_length=15, null=True, verbose_name='Description')),
                ('survey_slug', models.SlugField(max_length=40)),
                ('chronological_order', models.IntegerField(db_index=True, default=0)),
                ('datetime_start', models.DateTimeField(verbose_name='Start Date')),
                ('datetime_end', models.DateTimeField(verbose_name='End Date')),
            ],
            options={
                'ordering': ['survey_name'],
            },
        ),
    ]
