from main import *
from demographics_risk_form import DemographicsRiskForm
from partners_form import RecentPartnerForm, SecondPartnerForm, ThirdPartnerForm
from htc_visit_form import HtcVisitForm
from circumcision_form import CircumcisionForm
from hiv_testing_history_form import HivTestingHistoryForm
from last_hiv_record_form import LastHivRecordForm
from hiv_testing_counseling_form import HivTestingCounselingForm
from followup_contact_permission_form import FollowupContactPermissionForm
from htc_registration_form import HtcRegistrationForm
